name: Check Branch Name
on: [push]

jobs:
  branch_name:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check the name of the branch
        run: |
          echo 'Name of the branch is' ${{github.ref_name}}
  deploy:
    needs: branch_name
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Prod
        run: echo 'Deploying...'
