on: [push]

jobs:
  build:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    name: Check Branch Name
    runs-on: ubuntu-latest
    if: ${github.head_ref} != 'main'
    steps:
      - uses: actions/checkout@v3
      - name: Check if is the main branch
        run: |
          echo 'Name of the branch is' ${{env.BRANCH}}

      - name: Deploy
        run: |
          echo Deploy!!!
